name: Publish
on:
  push:
    branches: ['main']

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
      - run: npm install
